baseURL = "https://example.com"
canonifyURLs = true
languageCode = "en"
defaultContentLanguage = "en"

title = "Hugo Relearn Documentation"
theme = "hugo-theme-relearn"
# themesdir = "../.."
relativeURLs = true

[params]
  editURL = "https://github.com/McShelby/hugo-theme-relearn/edit/main/exampleSite/content/"
  description = "Documentation for Hugo Relearn Theme"
  author = "René Baron"

  # Currently we are english only. When adding German, set the flag to "false"
  # When false, the language switching button will dissappear from the sidebar.
  disableLanguageSwitchingButton = true

  # showVisitedLinks Links-Param is used in the _layouts/partials/menu-html file where the menu is rendered
  # on = display visited menu entries. 
  # you might toggle them off again wiht a click on the "cancel history" button at the end of the treeview. 
  showVisitedLinks = true

  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  titleSeparator = "::"
  themeVariant = "relearn"
  disableSeoHiddenPages = false

  # disableSearch is used in the menu to activate (= true) / dectivate (= false) the Search box
  # below the logo
  disableSearch = false

  ## Whether or not a click on the logo will navigate back to the homepage (= false) or not (= true)
  ## The language-specific Home URL is set below in the language settings.
  disableLandingPageButton = false

  # ShortCutTitle is the Title above the ShortCut-Icons for GitHub, Showcases, Credits, Tags, etc. 
  # Default TitleText = "More"	
  DisableShortcutsTitle = false



[outputs]
  # JSON Output is only required for the locally installed Lunr-Search-index. 
  # When you switch to an alternative Searchengeine - such as Algolia - make sure JSON is removed from the list!
  home = ["HTML", "RSS", "JSON"] 

[markup]
  [markup.highlight]
    style = "base16-snazzy" # choose a color theme or create your own
    guessSyntax = false     # if set to true, avoid unstyled code if no language was given but mermaid code fences will not work anymore

[markup.goldmark.renderer]
  unsafe= true

[Languages]
  [Languages.en]
    title = "Documentation for Hugo Relearn Theme"
    weight = 1

    languageName = "English"

    # Home-URL
    #        The URL where the navigation shall go when clicked on the Logo/Icon. 
    #        This value is read from the config.toml from the following section: 
    #        [Languages]
    #          [Languages.en]
    #            landingPageURL = "/"
    #
    #        Note here, that that the Home-URL can be set differently according to language    
    #        When not defined in the config.toml then then "/" is assumed as default URL
    landingPageURL = "/"
 
   landingPageName = "<i class='fas fa-home'></i> Home"


  ########################################################################################################
  ## Shortcuts
  ## Will generate the ShortCutLinks to common supporting links like the GitHub-Repo, ThemeShowcases
  ## Credits etc. 
  ##
  ## Shortcuts can also be used to link to specific internal pages like "Contacts" etc. 
  ##
  ## Icons are added in front-of the Link-Text with FontAwesome-classes 
  ## For details about the rendering of these NavigationLinks check the menu-partial9
  ##vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

  ## GitHub Theme-Repo where the Theme would be published
   ## [[Languages.en.menu.shortcuts]]
   ##   name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
   ##   identifier = "ds"
   ##   url = "https://github.com/McShelby/hugo-theme-relearn"
   ##   weight = 10

  ## Showcases
   ## [[Languages.en.menu.shortcuts]]
   ##  name = "<i class='fas fa-fw fa-camera'></i> Showcases"
   ##  url = "/showcase/"
   ##  weight = 11

  ## Hugo Online Documentation
  ## Showcases[[Languages.en.menu.shortcuts]]
    ## Showcasesname = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
    ## Showcasesidentifier = "hugodoc"
    ## Showcasesurl = "https://gohugo.io/"
    ## Showcasesweight = 20

  ## Direct Link to our internal ShortCut pages
  [[Languages.en.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-bullhorn'></i> TestLinks"
    url = "/linktests/"
    weight = 30

  ## Tags: Link to autogenerated Tags Overview Page
  [[Languages.en.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-tags'></i> Tags"
    url = "/tags/"
    weight = 40

  ########################################################################################################
  ## 
  ## 
  ##vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

  [Languages.pir]
    title = "Documentat'n fer Cap'n Hugo Relearrrn Theme"
    weight = 1
    languageName = "Arrr! Pirrrates"
    landingPageURL = "/pir/"
    landingPageName = "<i class='fas fa-home'></i> Arrr! Home"

  [[Languages.pir.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
    identifier = "ds"
    url = "https://github.com/McShelby/hugo-theme-relearn"
    weight = 10

  [[Languages.pir.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-camera'></i> Showcases"
    url = "/showcase/"
    weight = 11

  [[Languages.pir.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-bookmark'></i> Cap'n Hugo Documentat'n"
    identifier = "hugodoc"
    url = "https://gohugo.io/"
    weight = 20

  [[Languages.pir.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-bullhorn'></i> Crrredits"
    url = "/credits/"
    weight = 30

  [[Languages.pir.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-tags'></i> Arrr! Tags"
    url = "/tags/"
    weight = 40
